### ISSUE TITLE
2.3 Styles don't do anything

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/quick-start#14]
After adding styles to my `app.css` file, my app look exactly like it did before.

![ios simulator screen shot aug 5 2015 4 36 59 pm](https://cloud.githubusercontent.com/assets/686963/9098551/3a7591fc-3b90-11e5-876d-9081a1bf6d09.png)

**Comment by tjvantoll** [comment]
This is a {N} 1.2.0 bug. I updated the modules in Groceries to the latest from master which have a fix. If you try again it'll work.
